#TODO: What is this line of code doing
name: Deploy

#TODO: What is this block of code doing
on:
    push:
      branches: [main]
    pull_request:
      branches:
        - main
        
#TODO: What is this block of code doing   
jobs:
    ci:
      runs-on: ubuntu-latest
      strategy:
          matrix:
            node-version: [20.x, 22.x]
            mongodb-version: ['6.0', '7.0', '8.0']
      steps:
        - uses: actions/checkout@v3
        
        # Install dependencies
        - name: 🧰 Install Deps
          run: npm install
          working-directory: ./

        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.11.0
          with:
              mongodb-version: ${{ matrix.mongodb-version }}
              mongodb-replica-set: test-rs
              mongodb-port: 27017        
        # Run build
        - name: Run Build
          run: npm run build

        #seed file
        - name: Run seed
          run: node ./server/dist/seeds/seed.js

        # Start server in the background
        - name: Start Server
          run: |
            npm run start &
          working-directory: ./server
          env:
           MONGODB_URI: mongodb://localhost:27017/techquiz

         # Wait for server to be ready
        - name: Wait for Server to be Ready
          run: npx wait-on http://localhost:3001 --timeout 120000
        

        - name: Test
          run: npm run test

        - name: Test
          run: npm run test-component

   

        - name: Deploy
          env:
            SERVICE_ID: ${{ secrets.MY_RENDER_SERVICE_ID }}
            SERVICE_KEY: ${{ secrets.MY_RENDER_API_KEY }}
            
          run: |
            curl --request POST \
            --url 'https://api.render.com/v1/services/<$SERVICE_ID/deploys' \
            --header 'Authorization: Bearer $SERVICE_KEY' 

        - name: Testing varaibles
          env:
            SERVICE_ID: ${{ secrets.MY_RENDER_SERVICE_ID }}
            SERVICE_KEY: ${{ secrets.MY_RENDER_API_KEY }}
          run: |
              echo "  SERVICE_ID: $SERVICE_ID"
              echo " SERVICE_KEY: $SERVICE_KEY"

   
