# Name of workflow
name: Lint workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - staging

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm install
        working-directory: ./

      # Run build
      - name: Run Build
        run: npm run build

      # Start server in the background
      - name: Start Server
        run: npm run start &
        working-directory: ./server

      # Wait for server to be ready
      - name: Wait for Server to be Ready
        run: npx wait-on http://localhost:3001

      # Run tests
      - name: Run Tests
        run: npm run test