# Name of workflow
name: CI Workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - staging

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --bind_ip_all
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 60s
          --health-retries 10
        entrypoint: ["mongod", "--replSet", "test"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm install
        working-directory: ./

      # Run build
      - name: Run Build
        run: npm run build

      # Start server in the background
      - name: Start Server
        run: |
          npm run start &
        working-directory: ./server
        env:
          MONGODB_URI: mongodb://localhost:27017/techquiz

      # Wait for server to be ready
      - name: Wait for Server to be Ready
        run: npx wait-on http://localhost:3001 --timeout 120000

      # Run tests
      - name: Run Tests
        run: npm run test