# Name of workflow
name: CI Workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - staging

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        mongodb-version: ['6.0', '7.0', '8.0']

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x
          
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm install
        working-directory: ./

      # Run build
      - name: Run Build
        run: npm run build

      # Start server in the background
      - name: Start Server
        run: |
          npm run start &
        working-directory: ./server
        env:
          MONGODB_URI: mongodb://localhost:27017/techquiz

      # Wait for server to be ready
      - name: Wait for Server to be Ready
        run: npx wait-on http://localhost:3001 --timeout 120000

      # Run tests
      - name: Run Tests
        run: npm run test
